/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CmWrap: typeof import('./src/components/CmWrap.vue')['default']
    Debug: typeof import('./src/components/Debug.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
  }
}
